# Generated by Django 5.0.4 on 2024-08-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_mymodel_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='nationality',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
