# Generated by Django 5.0.4 on 2024-08-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_mymodel_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
            ],
        ),
    ]
